-- Migration: create global preset tables for default project and expense categories

CREATE TABLE IF NOT EXISTS public.project_category_presets (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(255) NOT NULL,
    description text,
    is_active boolean DEFAULT true,
    sort_order integer,
    CONSTRAINT project_category_presets_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.expense_category_presets (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_category_preset_id integer NOT NULL REFERENCES public.project_category_presets(id) ON DELETE CASCADE,
    name character varying(255) NOT NULL,
    description text,
    is_active boolean DEFAULT true,
    sort_order integer,
    CONSTRAINT expense_category_presets_name_per_preset UNIQUE (project_category_preset_id, name)
);

-- Seed project category presets
INSERT INTO public.project_category_presets (name, sort_order) VALUES
  ('Meals / Catering', 1),
  ('Transport / Logistics', 2),
  ('Farming & Agriculture', 3),
  ('Construction & Renovation', 4),
  ('Events & Functions', 5),
  ('Education & Training', 6),
  ('Healthcare & Medical', 7),
  ('ICT / Software', 8),
  ('Retail & Trading', 9),
  ('Community Development / NGO', 10),
  ('Maintenance & Utilities', 11),
  ('Business Operations / Admin', 12),
  ('Furniture & Interior Design', 13)
ON CONFLICT (name) DO NOTHING;

-- Seed expense category presets for each project category preset

-- 1. Meals / Catering
INSERT INTO public.expense_category_presets (project_category_preset_id, name, sort_order)
VALUES
  ((SELECT id FROM public.project_category_presets WHERE name = 'Meals / Catering'), 'Food Ingredients & Groceries', 1),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Meals / Catering'), 'Cooking Gas / Charcoal / Firewood', 2),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Meals / Catering'), 'Kitchen Supplies & Utensils', 3),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Meals / Catering'), 'Labor / Cooking Services', 4),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Meals / Catering'), 'Transport & Delivery', 5),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Meals / Catering'), 'Water & Drinks', 6),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Meals / Catering'), 'Packaging (plates, cups, takeaway boxes)', 7),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Meals / Catering'), 'Storage (coolers, fridges, ice)', 8)
ON CONFLICT (project_category_preset_id, name) DO NOTHING;

-- 2. Transport / Logistics
INSERT INTO public.expense_category_presets (project_category_preset_id, name, sort_order)
VALUES
  ((SELECT id FROM public.project_category_presets WHERE name = 'Transport / Logistics'), 'Fuel & Lubricants', 1),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Transport / Logistics'), 'Vehicle Maintenance & Repairs', 2),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Transport / Logistics'), 'Boda / Car Hire', 3),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Transport / Logistics'), 'Driver Allowances', 4),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Transport / Logistics'), 'Road Licenses, Insurance', 5),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Transport / Logistics'), 'Tyres, Batteries, Spare Parts', 6),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Transport / Logistics'), 'Parking & Toll Fees', 7),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Transport / Logistics'), 'Vehicle Tracking / Security', 8)
ON CONFLICT (project_category_preset_id, name) DO NOTHING;

-- 3. Farming & Agriculture
INSERT INTO public.expense_category_presets (project_category_preset_id, name, sort_order)
VALUES
  ((SELECT id FROM public.project_category_presets WHERE name = 'Farming & Agriculture'), 'Seeds & Seedlings', 1),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Farming & Agriculture'), 'Fertilizers & Chemicals', 2),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Farming & Agriculture'), 'Farm Tools & Equipment', 3),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Farming & Agriculture'), 'Labor (farm workers)', 4),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Farming & Agriculture'), 'Animal Feeds (poultry, cattle, goats)', 5),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Farming & Agriculture'), 'Veterinary Services', 6),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Farming & Agriculture'), 'Land Preparation (ploughing, digging)', 7),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Farming & Agriculture'), 'Irrigation & Water Supply', 8)
ON CONFLICT (project_category_preset_id, name) DO NOTHING;

-- 4. Construction & Renovation
INSERT INTO public.expense_category_presets (project_category_preset_id, name, sort_order)
VALUES
  ((SELECT id FROM public.project_category_presets WHERE name = 'Construction & Renovation'), 'Building Materials (cement, sand, bricks)', 1),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Construction & Renovation'), 'Labor (masons, painters, carpenters)', 2),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Construction & Renovation'), 'Machinery Hire (concrete mixer, excavator)', 3),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Construction & Renovation'), 'Site Supervision & Engineering', 4),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Construction & Renovation'), 'Transport of Materials', 5),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Construction & Renovation'), 'Safety Gear & Tools', 6),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Construction & Renovation'), 'Finishing Materials (tiles, paint, fittings)', 7),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Construction & Renovation'), 'Permits & Inspection Fees', 8)
ON CONFLICT (project_category_preset_id, name) DO NOTHING;

-- 5. Events & Functions
INSERT INTO public.expense_category_presets (project_category_preset_id, name, sort_order)
VALUES
  ((SELECT id FROM public.project_category_presets WHERE name = 'Events & Functions'), 'Venue Hire', 1),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Events & Functions'), 'Decoration & Setup', 2),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Events & Functions'), 'Sound System & DJ', 3),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Events & Functions'), 'Photography / Videography', 4),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Events & Functions'), 'Security Personnel', 5),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Events & Functions'), 'Meals & Catering', 6),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Events & Functions'), 'Chairs, Tents & Furniture Hire', 7),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Events & Functions'), 'Transport & Logistics', 8)
ON CONFLICT (project_category_preset_id, name) DO NOTHING;

-- 6. Education & Training
INSERT INTO public.expense_category_presets (project_category_preset_id, name, sort_order)
VALUES
  ((SELECT id FROM public.project_category_presets WHERE name = 'Education & Training'), 'Learning Materials (books, stationery)', 1),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Education & Training'), 'Trainers / Facilitators Fees', 2),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Education & Training'), 'Venue or Classroom Hire', 3),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Education & Training'), 'Meals & Refreshments', 4),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Education & Training'), 'Transport & Allowances', 5),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Education & Training'), 'Printing & Photocopying', 6),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Education & Training'), 'Certificates & Graduation Items', 7),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Education & Training'), 'Student Support Items', 8)
ON CONFLICT (project_category_preset_id, name) DO NOTHING;

-- 7. Healthcare & Medical
INSERT INTO public.expense_category_presets (project_category_preset_id, name, sort_order)
VALUES
  ((SELECT id FROM public.project_category_presets WHERE name = 'Healthcare & Medical'), 'Medical Supplies (bandages, gloves, etc.)', 1),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Healthcare & Medical'), 'Medicines & Vaccines', 2),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Healthcare & Medical'), 'Staff Allowances', 3),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Healthcare & Medical'), 'Medical Equipment Hire', 4),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Healthcare & Medical'), 'Transport / Ambulance Fuel', 5),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Healthcare & Medical'), 'Patient Meals', 6),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Healthcare & Medical'), 'Cleaning & Sanitation Supplies', 7),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Healthcare & Medical'), 'Registration / Licensing Fees', 8)
ON CONFLICT (project_category_preset_id, name) DO NOTHING;

-- 8. ICT / Software
INSERT INTO public.expense_category_presets (project_category_preset_id, name, sort_order)
VALUES
  ((SELECT id FROM public.project_category_presets WHERE name = 'ICT / Software'), 'Software Licenses', 1),
  ((SELECT id FROM public.project_category_presets WHERE name = 'ICT / Software'), 'Developer Labor / Contract Fees', 2),
  ((SELECT id FROM public.project_category_presets WHERE name = 'ICT / Software'), 'Cloud Hosting / Servers', 3),
  ((SELECT id FROM public.project_category_presets WHERE name = 'ICT / Software'), 'Internet Data', 4),
  ((SELECT id FROM public.project_category_presets WHERE name = 'ICT / Software'), 'Laptops & Equipment', 5),
  ((SELECT id FROM public.project_category_presets WHERE name = 'ICT / Software'), 'Testing Tools', 6),
  ((SELECT id FROM public.project_category_presets WHERE name = 'ICT / Software'), 'UI/UX Design Materials', 7),
  ((SELECT id FROM public.project_category_presets WHERE name = 'ICT / Software'), 'Maintenance & Support Costs', 8)
ON CONFLICT (project_category_preset_id, name) DO NOTHING;

-- 9. Retail & Trading
INSERT INTO public.expense_category_presets (project_category_preset_id, name, sort_order)
VALUES
  ((SELECT id FROM public.project_category_presets WHERE name = 'Retail & Trading'), 'Inventory Purchase (stock)', 1),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Retail & Trading'), 'Transport / Delivery of Goods', 2),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Retail & Trading'), 'Storage & Warehousing', 3),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Retail & Trading'), 'Shop Rent', 4),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Retail & Trading'), 'Staff Salaries', 5),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Retail & Trading'), 'Packaging Materials', 6),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Retail & Trading'), 'Marketing & Branding', 7),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Retail & Trading'), 'POS or Accounting Software', 8)
ON CONFLICT (project_category_preset_id, name) DO NOTHING;

-- 10. Community Development / NGO
INSERT INTO public.expense_category_presets (project_category_preset_id, name, sort_order)
VALUES
  ((SELECT id FROM public.project_category_presets WHERE name = 'Community Development / NGO'), 'Community Training Activities', 1),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Community Development / NGO'), 'Field Staff Allowances', 2),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Community Development / NGO'), 'Transport & Fuel', 3),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Community Development / NGO'), 'Program Materials', 4),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Community Development / NGO'), 'Monitoring & Evaluation', 5),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Community Development / NGO'), 'Stationery & Printing', 6),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Community Development / NGO'), 'Beneficiary Support Items', 7),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Community Development / NGO'), 'Communications (airtime, data)', 8)
ON CONFLICT (project_category_preset_id, name) DO NOTHING;

-- 11. Maintenance & Utilities
INSERT INTO public.expense_category_presets (project_category_preset_id, name, sort_order)
VALUES
  ((SELECT id FROM public.project_category_presets WHERE name = 'Maintenance & Utilities'), 'Electrical Repairs', 1),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Maintenance & Utilities'), 'Plumbing Repairs', 2),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Maintenance & Utilities'), 'Cleaning Supplies', 3),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Maintenance & Utilities'), 'Security Services', 4),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Maintenance & Utilities'), 'Generator Fuel', 5),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Maintenance & Utilities'), 'Water Bills', 6),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Maintenance & Utilities'), 'Electricity Bills', 7),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Maintenance & Utilities'), 'Waste Collection', 8)
ON CONFLICT (project_category_preset_id, name) DO NOTHING;

-- 12. Business Operations / Admin
INSERT INTO public.expense_category_presets (project_category_preset_id, name, sort_order)
VALUES
  ((SELECT id FROM public.project_category_presets WHERE name = 'Business Operations / Admin'), 'Staff Salaries & Wages', 1),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Business Operations / Admin'), 'Office Rent', 2),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Business Operations / Admin'), 'Airtime & Internet', 3),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Business Operations / Admin'), 'Stationery', 4),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Business Operations / Admin'), 'Legal & Accounting Fees', 5),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Business Operations / Admin'), 'Utilities (water, power)', 6),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Business Operations / Admin'), 'Transport Allowances', 7),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Business Operations / Admin'), 'Office Supplies', 8)
ON CONFLICT (project_category_preset_id, name) DO NOTHING;

-- 13. Furniture & Interior Design
INSERT INTO public.expense_category_presets (project_category_preset_id, name, sort_order)
VALUES
  ((SELECT id FROM public.project_category_presets WHERE name = 'Furniture & Interior Design'), 'Furniture Materials (wood, boards, fabrics, foam)', 1),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Furniture & Interior Design'), 'Labor (carpenters, upholsterers, painters)', 2),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Furniture & Interior Design'), 'Interior Décor Items (curtains, rugs, lighting, art)', 3),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Furniture & Interior Design'), 'Tools & Equipment (saws, drills, sanders)', 4),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Furniture & Interior Design'), 'Transport & Delivery of Furniture', 5),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Furniture & Interior Design'), 'Finishing Materials (varnish, paint, glue, polish)', 6),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Furniture & Interior Design'), 'Installation Costs (fixing shelves, curtain rods, fittings)', 7),
  ((SELECT id FROM public.project_category_presets WHERE name = 'Furniture & Interior Design'), 'Design & Consultation Fees', 8)
ON CONFLICT (project_category_preset_id, name) DO NOTHING;
